// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class CursorSettingsStatus {
    "path": string;
    "found": boolean;
    "error"?: string;
    "proxySet": boolean;
    "proxyValue"?: string;
    "strictSSLOff": boolean;
    "proxySupportOn": boolean;
    "systemCertsV2On": boolean;
    "useHttp1": boolean;
    "disableHttp2": boolean;
    "proxyKerberos": boolean;

    /** Creates a new CursorSettingsStatus instance. */
    constructor($$source: Partial<CursorSettingsStatus> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("found" in $$source)) {
            this["found"] = false;
        }
        if (!("proxySet" in $$source)) {
            this["proxySet"] = false;
        }
        if (!("strictSSLOff" in $$source)) {
            this["strictSSLOff"] = false;
        }
        if (!("proxySupportOn" in $$source)) {
            this["proxySupportOn"] = false;
        }
        if (!("systemCertsV2On" in $$source)) {
            this["systemCertsV2On"] = false;
        }
        if (!("useHttp1" in $$source)) {
            this["useHttp1"] = false;
        }
        if (!("disableHttp2" in $$source)) {
            this["disableHttp2"] = false;
        }
        if (!("proxyKerberos" in $$source)) {
            this["proxyKerberos"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CursorSettingsStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): CursorSettingsStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CursorSettingsStatus($$parsedSource as Partial<CursorSettingsStatus>);
    }
}

export class DailyUsageEntry {
    /**
     * YYYY-MM-DD in local time
     */
    "date": string;
    "promptTokens": number;
    "completionTokens": number;

    /** Creates a new DailyUsageEntry instance. */
    constructor($$source: Partial<DailyUsageEntry> = {}) {
        if (!("date" in $$source)) {
            this["date"] = "";
        }
        if (!("promptTokens" in $$source)) {
            this["promptTokens"] = 0;
        }
        if (!("completionTokens" in $$source)) {
            this["completionTokens"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DailyUsageEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): DailyUsageEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DailyUsageEntry($$parsedSource as Partial<DailyUsageEntry>);
    }
}

export class ModelAdapterConfig {
    "displayName": string;
    "type": string;
    "baseURL": string;
    "apiKey": string;
    "modelID": string;
    "contextWindow"?: string;
    "reasoningEffort"?: string;
    "serviceTier"?: string;
    "maxOutputTokens"?: number;
    "thinkingBudget"?: number;
    "retryCount"?: number;
    "retryInterval"?: number;
    "timeout"?: number;
    "notes"?: string;
    "lastTestResult"?: string;
    "lastTestedAt"?: number;

    /** Creates a new ModelAdapterConfig instance. */
    constructor($$source: Partial<ModelAdapterConfig> = {}) {
        if (!("displayName" in $$source)) {
            this["displayName"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("baseURL" in $$source)) {
            this["baseURL"] = "";
        }
        if (!("apiKey" in $$source)) {
            this["apiKey"] = "";
        }
        if (!("modelID" in $$source)) {
            this["modelID"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModelAdapterConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): ModelAdapterConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModelAdapterConfig($$parsedSource as Partial<ModelAdapterConfig>);
    }
}

export class ModelUsageEntry {
    "model": string;
    "provider": string;
    "promptTokens": number;
    "completionTokens": number;
    "turnCount": number;

    /** Creates a new ModelUsageEntry instance. */
    constructor($$source: Partial<ModelUsageEntry> = {}) {
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("promptTokens" in $$source)) {
            this["promptTokens"] = 0;
        }
        if (!("completionTokens" in $$source)) {
            this["completionTokens"] = 0;
        }
        if (!("turnCount" in $$source)) {
            this["turnCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModelUsageEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): ModelUsageEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModelUsageEntry($$parsedSource as Partial<ModelUsageEntry>);
    }
}

export class ProxyState {
    "running": boolean;
    "listenAddr": string;
    "baseURL": string;
    "startedAt": number;
    "caFingerprint": string;
    "caPath": string;
    "caInstalled": boolean;
    "caInstallMode"?: string;
    "caWarning"?: string;
    "lastError"?: string;

    /** Creates a new ProxyState instance. */
    constructor($$source: Partial<ProxyState> = {}) {
        if (!("running" in $$source)) {
            this["running"] = false;
        }
        if (!("listenAddr" in $$source)) {
            this["listenAddr"] = "";
        }
        if (!("baseURL" in $$source)) {
            this["baseURL"] = "";
        }
        if (!("startedAt" in $$source)) {
            this["startedAt"] = 0;
        }
        if (!("caFingerprint" in $$source)) {
            this["caFingerprint"] = "";
        }
        if (!("caPath" in $$source)) {
            this["caPath"] = "";
        }
        if (!("caInstalled" in $$source)) {
            this["caInstalled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProxyState instance from a string or object.
     */
    static createFrom($$source: any = {}): ProxyState {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProxyState($$parsedSource as Partial<ProxyState>);
    }
}

/**
 * UsageStats is the aggregate token-use snapshot the Stats tab in the Wails
 * frontend displays. It's computed on demand from the on-disk history root
 * (%APPDATA%/cursorbridge/history/<conversationID>/turns/* /summary.json),
 * so the values always reflect the complete recorded conversation corpus —
 * not just the live in-memory session window.
 */
export class UsageStats {
    "totalPromptTokens": number;
    "totalCompletionTokens": number;
    "totalTokens": number;
    "conversationCount": number;
    "turnCount": number;
    "perModel": ModelUsageEntry[];
    "last7Days": DailyUsageEntry[];

    /** Creates a new UsageStats instance. */
    constructor($$source: Partial<UsageStats> = {}) {
        if (!("totalPromptTokens" in $$source)) {
            this["totalPromptTokens"] = 0;
        }
        if (!("totalCompletionTokens" in $$source)) {
            this["totalCompletionTokens"] = 0;
        }
        if (!("totalTokens" in $$source)) {
            this["totalTokens"] = 0;
        }
        if (!("conversationCount" in $$source)) {
            this["conversationCount"] = 0;
        }
        if (!("turnCount" in $$source)) {
            this["turnCount"] = 0;
        }
        if (!("perModel" in $$source)) {
            this["perModel"] = [];
        }
        if (!("last7Days" in $$source)) {
            this["last7Days"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UsageStats instance from a string or object.
     */
    static createFrom($$source: any = {}): UsageStats {
        const $$createField5_0 = $$createType1;
        const $$createField6_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("perModel" in $$parsedSource) {
            $$parsedSource["perModel"] = $$createField5_0($$parsedSource["perModel"]);
        }
        if ("last7Days" in $$parsedSource) {
            $$parsedSource["last7Days"] = $$createField6_0($$parsedSource["last7Days"]);
        }
        return new UsageStats($$parsedSource as Partial<UsageStats>);
    }
}

export class UserConfig {
    "baseURL": string;
    "modelAdapters": ModelAdapterConfig[];
    "activeModelID"?: string;
    "commitModelID"?: string;
    "reviewModelID"?: string;

    /**
     * CloseAction remembers what the user picked in the "Quit or minimize
     * to tray?" dialog. Empty = never answered, show the dialog on close.
     * "quit" = shut the proxy down and exit. "tray" = hide to system tray.
     */
    "closeAction"?: string;

    /**
     * MaxLoopRounds caps the agent tool-call loop rounds. 0 = no cap (native
     * Cursor behaviour — the client controls when to stop). A positive value
     * limits each agentic turn to that many LLM round-trips.
     */
    "maxLoopRounds"?: number;

    /**
     * MaxTurnDurationMin caps the wall-clock time per agentic turn. 0 = no
     * cap (native behaviour). A positive value sets the cap in minutes.
     */
    "maxTurnDurationMin"?: number;

    /**
     * ToolExecTimeoutSec caps how long the agent waits for Cursor's IDE to
     * execute a tool and return the result. 0 = use defaults (30s for agent
     * and BugBot, 2min for BackgroundComposer).
     */
    "toolExecTimeoutSec"?: number;

    /** Creates a new UserConfig instance. */
    constructor($$source: Partial<UserConfig> = {}) {
        if (!("baseURL" in $$source)) {
            this["baseURL"] = "";
        }
        if (!("modelAdapters" in $$source)) {
            this["modelAdapters"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UserConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): UserConfig {
        const $$createField1_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("modelAdapters" in $$parsedSource) {
            $$parsedSource["modelAdapters"] = $$createField1_0($$parsedSource["modelAdapters"]);
        }
        return new UserConfig($$parsedSource as Partial<UserConfig>);
    }
}

// Private type creation functions
const $$createType0 = ModelUsageEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = DailyUsageEntry.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = ModelAdapterConfig.createFrom;
const $$createType5 = $Create.Array($$createType4);
