// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ApplyCursorTweaks(): $CancellablePromise<$models.CursorSettingsStatus> {
    return $Call.ByID(2451285814).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ConfigDir(): $CancellablePromise<string> {
    return $Call.ByID(843945708);
}

export function ExportCAPEM(): $CancellablePromise<string> {
    return $Call.ByID(203871885);
}

export function GetCloseAction(): $CancellablePromise<string> {
    return $Call.ByID(1704270557);
}

export function GetCursorSettingsStatus(): $CancellablePromise<$models.CursorSettingsStatus> {
    return $Call.ByID(2580388400).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetState(): $CancellablePromise<$models.ProxyState> {
    return $Call.ByID(2062715530).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetUsageStats returns the aggregate token-use snapshot the Stats tab in the
 * Wails UI renders. Computed on demand from disk; safe to call any time.
 */
export function GetUsageStats(): $CancellablePromise<$models.UsageStats> {
    return $Call.ByID(2512809111).then(($result: any) => {
        return $$createType2($result);
    });
}

export function InstallCA(): $CancellablePromise<$models.ProxyState> {
    return $Call.ByID(2435582922).then(($result: any) => {
        return $$createType1($result);
    });
}

export function LoadUserConfig(): $CancellablePromise<$models.UserConfig> {
    return $Call.ByID(3175757426).then(($result: any) => {
        return $$createType3($result);
    });
}

export function OpenSettingsFolder(): $CancellablePromise<void> {
    return $Call.ByID(903560110);
}

export function RequestHide(): $CancellablePromise<void> {
    return $Call.ByID(949249008);
}

export function RequestQuit(): $CancellablePromise<void> {
    return $Call.ByID(1467254095);
}

export function RevertCursorTweaks(): $CancellablePromise<$models.CursorSettingsStatus> {
    return $Call.ByID(1104575934).then(($result: any) => {
        return $$createType0($result);
    });
}

export function SaveUserConfig(cfg: $models.UserConfig): $CancellablePromise<void> {
    return $Call.ByID(3584929903, cfg);
}

export function SetBaseURL(url: string): $CancellablePromise<$models.ProxyState> {
    return $Call.ByID(1520446905, url).then(($result: any) => {
        return $$createType1($result);
    });
}

export function SetCloseAction(action: string): $CancellablePromise<void> {
    return $Call.ByID(3901340737, action);
}

export function SetHideCallback(cb: any): $CancellablePromise<void> {
    return $Call.ByID(3459720686, cb);
}

export function SetQuitCallback(cb: any): $CancellablePromise<void> {
    return $Call.ByID(1750542809, cb);
}

export function SetStateCallback(cb: any): $CancellablePromise<void> {
    return $Call.ByID(2396298169, cb);
}

export function Shutdown(): $CancellablePromise<void> {
    return $Call.ByID(4088986773);
}

export function StartProxy(): $CancellablePromise<$models.ProxyState> {
    return $Call.ByID(4158454875).then(($result: any) => {
        return $$createType1($result);
    });
}

export function StopProxy(): $CancellablePromise<$models.ProxyState> {
    return $Call.ByID(2456187969).then(($result: any) => {
        return $$createType1($result);
    });
}

export function TestAdapter(index: number): $CancellablePromise<$models.ModelAdapterConfig> {
    return $Call.ByID(322325058, index).then(($result: any) => {
        return $$createType4($result);
    });
}

export function UninstallCA(): $CancellablePromise<$models.ProxyState> {
    return $Call.ByID(988888115).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.CursorSettingsStatus.createFrom;
const $$createType1 = $models.ProxyState.createFrom;
const $$createType2 = $models.UsageStats.createFrom;
const $$createType3 = $models.UserConfig.createFrom;
const $$createType4 = $models.ModelAdapterConfig.createFrom;
